// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetCurrentConfig():Promise<config.DMXAPIConfig>;

export function GetPresetModels():Promise<Array<string>>;

export function SaveConfig(arg1:string,arg2:string,arg3:string):Promise<void>;
